version: '2'

services:

  aspnetapp:
    build: ./aspnetapp
    image: docker-compose-demo/aspnetapp:dev
    networks:
      - backend

  nodejsapp:
    build: ./nodejsapp
    image: docker-compose-demo/nodejsapp:dev
    networks:
      - backend

  pyapp:
    build: ./pyapp
    image: docker-compose-demo/pyapp:dev
    networks:
      - backend

  lighttpd:
    build: ./lighttpd
    image: docker-compose-demo/lighttpd:dev
    networks:
      - backend
      - frontend
    volumes:
      - ./www:/var/www/localhost/htdocs

  proxy:
    build: ./proxy
    image: docker-compose-demo/proxy:dev
    ports:
      - "443:443"
      - "80:80"
    networks:
      - backend
      - frontend
    depends_on:
      - lighttpd
      - aspnetapp
      - nodejsapp
      - pyapp

networks:
  frontend:
  backend: