version: '3.3'

services:

  aspnetapp:
    build: ./aspnetapp
    image: polys/docker-compose-demo-aspnet:dev
    networks:
      - backend

  nodejsapp:
    build: ./nodejsapp
    image: polys/docker-compose-demo-nodejs:dev
    networks:
      - backend

  pyapp:
    build: ./pyapp
    image: polys/docker-compose-demo-python:dev
    networks:
      - backend

  web:
    build: ./www
    image: polys/docker-compose-demo-web:dev
    networks:
      - backend
      - frontend

  proxy:
    build: ./proxy
    image: polys/docker-compose-demo-proxy:dev
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend
    depends_on:
      - web
      - aspnetapp
      - nodejsapp
      - pyapp

networks:
  frontend:
  backend: