version: '3.3'

services:

  auth:
    image: polys/docker-compose-demo-auth:dev

  aspnetapp:
    image: polys/docker-compose-demo-aspnet:dev

  nodejsapp:
    image: polys/docker-compose-demo-nodejs:dev

  pythonapp:
    image: polys/docker-compose-demo-python:dev

  web:
    image: polys/docker-compose-demo-web:dev

  proxy:
    image: polys/docker-compose-demo-proxy:dev
    ports:
      - "80:80"
